### ISSUE TITLE
Purchases not appearing in activity feed

### ISSUE THREAD

**Issue by TheodoreMichels** [cashmusic/platform#1066]
I'm currently trying to test out the activity feed (and quantity property for commerce items) but it doesn't seem to be working.

I have a "Test Purchase Item" that costs $0.00 - and I've set the quantity to 20.
When I go to my page and "purchase" the item, I see the "Thank you! Here's your download..." message (no errors in JS console either).

But if I log out and log back in, there's no change in the activity feed on the Main Page. I still see "This is your activity feed. etc..."

I've also added my PayPal info in the Commerce settings.
Does this have anything to do with the cost being $0.00?

Thanks for your time,
Teddy

**Comment by paperscissors** [comment]
Hi Teddy, wondering, is the purchase a digital only item? It's possible we're only showing items marked as unfulfilled, which digital orders always get marked as fulfilled right when the order completes.

Best,
Tom

**Comment by TheodoreMichels** [comment]
Hey again Tom - I tried digital only first, but then tried a "physical" item as well - added different size options, etc... Still not getting anything in the feed.

Also, I just realized that when I choose to purchase the item, it never asks me for a shipping address - it just shows the confirmation message. Maybe there's something I need to change on the back end to get that to show up?
Or maybe I should try using a "Store" element rather than a "Single Purchase"?

Thanks again for your time,
Teddy

**Comment by paperscissors** [comment]
Hey Teddy,

I do remember there being a setting that I'd accidentally skip while testing any purchase element that would make the shipping dialog not show up--- possibly it's not setting the shipping regions?

I can't remember off the top of my head but it is something I've done before. I'll try to recreate in the morning.

Otherwise the checkout flow is identical for single vs. store elements.

Thanks!
Tom

**Comment by TheodoreMichels** [comment]
I did try setting the shipping regions, but that didn't change anything.
However, setting the price of the item to $0.01 DID make the shipping dialogue appear. So I guess there's a conditional in there somewhere that's preventing it from showing up on items with 0 cost?

I haven't actually gone through with adding all my info, etc... but I imagine that would make the order appear in the activity feed?

Teddy

**Comment by paperscissors** [comment]
Bingo, it is the $0 flag. The issue here is that the shipping info is dependent on the payment submission for serialization. So if the price is set to $0 the shipping just doesn't show up, because then there's (currently) no place set to serialize it to.

We could change how this flows but it's a pretty outlying use case so it's pretty low on the list for now.

I don't remember the exact order of operations but I think either way it would still not show new orders on  the activity feed unless a) they were physical and b) they were unfulfilled (requires a).

I'd like in the near future for better stats broken down on the activity feed, but I think in the meantime there isn't a way around this on our production server platform.

I do a lot of tests like what you're doing with both a vagrant box and our testing server, where we've got PayPal and Stripe testing mode turned on--- so you can do sandbox payments to get results like what you're trying to do.

Hope that clears up that mystery. Wish I could be of more help here other than suggesting using the Vagrant box we've got setup for local tests for now: https://github.com/cashmusic/rackspace-template

Best and thanks,
Tom

**Comment by TheodoreMichels** [comment]
Ahh ok - that makes sense.
Totally understand that it's not a big priority. The only practical reason I could see to change it might be for promotional reasons. Something like, "Hey fans, we've got a new t-shirt in our store! The first 20 visitors can get it for free!"
Just to drive traffic to the site/store - might be an option worth having. But I realize that's another matter entirely.

So yes anyway that clears things up, at least - and thanks for the link to the VMs - I may try that setup.

Thanks again for your time!
Teddy
