### ISSUE TITLE
After "Vagrant Up"

### ISSUE THREAD

**Issue by Zodzie** [cashmusic/platform#1067]
Virtualbox: Version 5.0.8 r103449

"vagrant up" on Mac, OS X El Capitan

inside system, /var/log/apache2/error.log

[Thu May 04 04:57:29 2017] [error] [client 10.0.2.2] PHP Parse error:  syntax error, unexpected '[' in /vagrant/framework/classes/core/CASHSystem.php on line 630

and 500 error from host browser.

Please assist.

**Comment by paperscissors** [comment]
Hi there,

We're actually right in the process of doing some platform upgrades that require a newer version of PHP than that Vagrant box supports. I think the PHP version on that box is 5.2 actually, so that's why you're getting that error. You must have provisioned that box right before we sunset the Vagrantfile from our repo.

There is a separate repo for a newer Vagrant box that we haven't folded into the repo here: https://github.com/cashmusic/rackspace-template

It has an up to date PHP version. It's a work in progress on some levels but we use it in house for dev work so it definitely does work for day to day.

Be sure to look at the part about `rsync-auto` on the README file.

Thanks!
