### ISSUE TITLE
"Translation: SPANISH"

### ISSUE THREAD

**Issue by JavierGallego** [cashmusic/platform#1130]
I Can help to translate the software in spanish lang, but I can't install the software in our vps, you can help me to install the software and the tools and I can translate the language a publish.

**Comment by paperscissors** [comment]
Hey Javier, 

There is a pre-beta Vagrant box here that you can use if you want to run via Vagrant: https://github.com/cashmusic/rackspace-template

Otherwise I think the main thing you need to do on your own server is:

* In the Platform codebase, copy framework/settings/cashmusic_template.ini.php to framework/settings/cashmusic.ini.php
* change the default settings in the database_connection to your own MySQL database
* Set the api URL to be your local machine URL but with the /api endpoint
* You'll need to set connection credentials for anything you want to try to use, in the connections.json file located in the framework/settings folder
* DB schema is located here: https://github.com/cashmusic/platform/blob/master/framework/settings/sql/cashmusic_db.sql

I did actually start a spanish translation on a branch but it's really behind the current master branch, so it might make sense for you to just start a new one.

Thanks!
Tom

**Comment by JavierGallego** [comment]
My shared host can't use vagrant...., but I see in the documentation the software have a easy web intaller?, when I try to download a 404 error page display.... Manual configuration is easy I think, I can try... I can make a native translation of the script... I try to install and them translate is not to difficult I think...

**Comment by paperscissors** [comment]
That makes sense.

I honestly don't know anything about the web installer. You'd be better off setting it up manually.

The web server should actually point to `/interfaces/public` I believe, and not the root of the platform. That's probably why you're getting a 404.

**Comment by JavierGallego** [comment]
I try with the install via make install, but not work, and them [here](http://cashmusic.github.io/platform/#setup) I try to download the web installer but redirect to a 404 page.... :'(

**Comment by paperscissors** [comment]
Yes, I think that documentation is quite old and in need of updating. That install script is from before my time at CASH.

I'd recommend doing a local git clone of the Github repo, or if you can't do that, download the ZIP of the platform and follow the steps I've mentioned above:

https://github.com/cashmusic/platform

**Comment by JavierGallego** [comment]
Ok I try thanks for your help! :)
