### ISSUE TITLE
Translations in general

### ISSUE THREAD

**Issue by romero350** [cashmusic/platform#1259]
Hi again!

First, I want to apologize because I have not been able to continue the Spanish translations yet but I will get to them :)

Second, as you noticed, there are some people wanting to translate your project to several languages. This is due to https://utopian.io, an online platform that rewards contributions on Open Source project as yours. As an Utopian Moderator for translations category, I apologize if, by this, the project gets flooded with Pull Requests for translating it.

Being that the case, if you ever need help to review those translations you can contact me or come to our Discord Server at https://discord.gg/uTyJkNm.

Third, I recommend you to always check all translations deeply (hence why I offer our help to proofread them) because there are some contributors doing bad translations to try to get rewarded (not that any of those is in your project yet).

Take care. You are really nice and attentive people.

**Comment by paperscissors** [comment]
Hey @romero350, thanks for checking in, it's much appreciated!

I did find utopian.io through some clicking through some of the first wave of translation offers—I appreciate you filling in the blanks.

I will definitely take you up on that offer to QA some of these translations. As new contributions have come in I have done some cursory checks with Google Translate to see if any of the contributions match the Google output verbatim. I figure that's a good first benchmark, and it looks like roughly 90% of what we've gotten so far does not match, so it looks good as far as not using machine learning to translate.

I don't remember which matched off the top of my head, but there was definitely one where there were new files translated and PRed every thirty seconds, which obviously is a red flag.

I'll be in touch, hopefully we can look through and fold some of these in soon. Probably Spanish first, because I can read that just fine and it looks great! We are very excited by this, we've wanted to do translations for years. It is overwhelming but hopefully worth it in the end!

Best,
Tom
