### ISSUE TITLE
'Edit Custom Embed' Button Bug

### ISSUE THREAD

**Issue by christopherleckie** [cashmusic/platform#650]
When you want to edit a custom embed template and switch to the custom embed style the 'Edit custom embed' button appears as it should. If you save the template changes in the Modal window that appears the edit button then disappears. This means you then have to change the embed style dropdown to a different state and click 'change style' and then repeat the process to return to the custom embed for the  button to reappear so you can make further changes.

The button should always be show when that state is selected in the embed style dropdown so re-editing is possible at any time.

![screen shot 2015-04-02 at 10 17 46](https://cloud.githubusercontent.com/assets/5073839/6969223/aede9182-d921-11e4-84b9-b749fbb44a28.png)

**Comment by jessevondoom** [comment]
does a page reload fix it or no?

**Comment by christopherleckie** [comment]
nope :(

**Comment by jessevondoom** [comment]
Weird. Then there's a much bigger issue than just state. I'll look into it.

**Comment by jessevondoom** [comment]
Sounds like the edited template is somehow disassociated with the element on save, pushing us back to default. Not sure why but I'll look into it ASAP.

**Comment by jessevondoom** [comment]
Narrowed it down to an issue with the switchblock button. (The one that swaps based on values of a dropdown.) Luckily it's not separating the custom embed from the element so that's a big deal. Changing away then changing back SHOULD reset the process (in the current flow at least) so this looks more like a JS bug not allowing a second edit. Was concerned we were fully breaking custom embeds.
