### ISSUE TITLE
change "FAQ's" in help pulldown menu to "How-To's"

### ISSUE THREAD

**Issue by westincash** [cashmusic/platform#954]
They aren't formatted as questions, so the term "FAQ's" isn't accurate.

**Comment by kabirnagral** [comment]
I don't see the FAQs anywhere, what's the directory you're referring to?

**Comment by kabirnagral** [comment]
I'm not sure how to test it, but I'm sure the fix is a simple fix in interfaces/admin/ui/default/template.mustache. I'm submitting a work in progress pull request with the change without testing (although it's fairly straightforward and I'm pretty confident that I've fixed the problem) because I'm not sure how to go about testing and running the code. #1186
